### ISSUE TITLE
Unit test?

### ISSUE THREAD

**Issue by daniel-cottone** [apex/node-apex#8]
How can I unit test modules using this wrapper? For example I am trying to test this with mocha and I keep getting:

```
TypeError: ctx.fail is not a function
      at node_modules/apex.js/index.js:15:11
      at Context.<anonymous> (.tmp/mocha-webpack/b2445ac84435dc5890ee678f8f0a5f8d/b2445ac84435dc5890ee678f8f0a5f8d-output.js:97:24)
```

**Comment by leggsimon** [comment]
Did you happen to solve this? I'm getting this now...
